import './globals.css'
import type { Metadata } from 'next'
import { pretendard } from '@/lib/font'

export const metadata: Metadata = {
  title: 'JSGO',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="min-h-screen">{children}</body>
    </html>
  )
}
